cd data
mkdir ECD
cd ECD
wget https://rpg.ifi.uzh.ch/datasets/davis/boxes_6dof.bag
wget https://rpg.ifi.uzh.ch/datasets/davis/calibration.bag
wget https://rpg.ifi.uzh.ch/datasets/davis/dynamic_6dof.bag
wget https://rpg.ifi.uzh.ch/datasets/davis/office_zigzag.bag
wget https://rpg.ifi.uzh.ch/datasets/davis/poster_6dof.bag
wget https://rpg.ifi.uzh.ch/datasets/davis/shapes_6dof.bag
wget https://rpg.ifi.uzh.ch/datasets/davis/slider_depth.bag