cd data
mkdir FPVDR
cd FPVDR
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_1_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_2_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_3_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_4_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_9_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_11_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_12_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_13_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_14_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_45_16_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_3_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_5_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_6_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_7_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_8_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_9_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_10_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_11_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/indoor_forward_12_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_1_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_2_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_3_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_5_davis_with_gt.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_6_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_9_davis.bag
wget http://rpg.ifi.uzh.ch/datasets/uzh-fpv-newer-versions/v3/outdoor_forward_10_davis.bag
