cd data
mkdir MVSEC
cd MVSEC
wget http://visiondata.cis.upenn.edu/mvsec/indoor_flying/indoor_flying1_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/indoor_flying/indoor_flying2_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/indoor_flying/indoor_flying3_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/indoor_flying/indoor_flying4_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/outdoor_day/outdoor_day1_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/outdoor_day/outdoor_day2_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/outdoor_night/outdoor_night1_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/outdoor_night/outdoor_night2_data.bag
wget http://visiondata.cis.upenn.edu/mvsec/outdoor_night/outdoor_night3_data.bag